#!/bin/sh

javac -cp commons-cli-1.2.jar MiCi.java
jar -cvfm mici.jar Manifest.txt MiCi.class commons-cli-1.2.jar
DIR=mici-`cat VERSION`
mkdir $DIR
mv mici.jar $DIR
cp run_mici* $DIR
zip -r $DIR.zip $DIR
rm -Rf $DIR
